// src/utils/regionales.js

export const REGIONALES = {
    AMAZONAS: { LETICIA: "Reg_Centro Oriente" },
    ANTIOQUIA: {
        MEDELLIN: "Reg_Medellin",
        ENVIGADO: "Reg_Medellin",
        RIONEGRO: "Reg_Medellin",
        "PUERTO BERRIO": "Reg_Medellin",
        SABANETA: "Reg_Medellin",
        BELLO: "Reg_Medellin",
        CAUCASIA: "Reg_Medellin",
        RETIRO: "Reg_Medellin",
        APARTADO: "Reg_Medellin",
        CALDAS: "Reg_Medellin",
        ITAGUI: "Reg_Medellin",
        "LA CEJA": "Reg_Medellin",
        AMAGA: "Reg_Medellin",
        MACEO: "Reg_Medellin",
        "CIUDAD BOLIVAR": "Reg_Medellin",
        "EL SANTUARIO": "Reg_Medellin",
        CISNEROS: "Reg_Medellin",
        GIRARDOTA: "Reg_Medellin",
        JARDIN: "Reg_Medellin",
        CARAMANTA: "Reg_Medellin",
        ARBOLETES: "Reg_Medellin",
        TARSO: "Reg_Medellin",
        "SANTAFE DE ANTIOQUIA": "Reg_Medellin",
        EBEJICO: "Reg_Medellin",
        BURITICA: "Reg_Medellin",
    },
    ARAUCA: {
        ARAUCA: "Reg_Bucaramanga",
        ARAUQUITA: "Reg_Bucaramanga",
        SARAVENA: "Reg_Bucaramanga",
        TAME: "Reg_Bucaramanga",
    },
    ATLANTICO: {
        BARRANQUILLA: "Reg_Barranquilla",
        "PUERTO COLOMBIA": "Reg_Barranquilla",
        SOLEDAD: "Reg_Barranquilla",
        BARANOA: "Reg_Barranquilla",
        SABANALARGA: "Reg_Barranquilla",
        USIACURI: "Reg_Barranquilla",
    },
    BOLIVAR: {
        CARTAGENA: "Reg_Barranquilla",
        MOMPOS: "Reg_Barranquilla",
        MAGANGUE: "Reg_Barranquilla",
    },
    BOYACA: {
        TUNJA: "Reg_Centro Oriente",
        SOGAMOSO: "Reg_Centro Oriente",
        DUITAMA: "Reg_Centro Oriente",
        MIRAFLORES: "Reg_Centro Oriente",
        GARAGOA: "Reg_Centro Oriente",
        "PUERTO BOYACA": "Reg_Centro Oriente",
        MONIQUIRA: "Reg_Centro Oriente",
        CHIQUINQUIRA: "Reg_Centro Oriente",
        NOBSA: "Reg_Centro Oriente",
        TIBASOSA: "Reg_Centro Oriente",
        TIBANA: "Reg_Centro Oriente",
        "SAN JOSE DE PARE": "Reg_Centro Oriente",
        PAIPA: "Reg_Centro Oriente",
        "PAZ DE RIO": "Reg_Centro Oriente",
        MONGUI: "Reg_Centro Oriente",
        SOATA: "Reg_Centro Oriente",
        RAMIRIQUI: "Reg_Centro Oriente",
        "VILLA DE LEYVA": "Reg_Centro Oriente",
        "EL COCUY": "Reg_Centro Oriente",
    },
    CALDAS: {
        MANIZALES: "Reg_Medellin",
        "LA DORADA": "Reg_Medellin",
        RIOSUCIO: "Reg_Medellin",
        ANSERMA: "Reg_Medellin",
        SALAMINA: "Reg_Medellin",
        AGUADAS: "Reg_Medellin",
        PACORA: "Reg_Medellin",
        MANZANARES: "Reg_Medellin",
        PENSILVANIA: "Reg_Medellin",
        SUPIA: "Reg_Medellin",
        CHINCHINA: "Reg_Medellin",
        ARANZAZU: "Reg_Medellin",
        FILADELFIA: "Reg_Medellin",
        VICTORIA: "Reg_Medellin",
        VITERBO: "Reg_Medellin",
    },
    CAQUETA: {
        FLORENCIA: "Reg_Centro Oriente",
        "BELEN DE LOS ANDAQUIES": "Reg_Centro Oriente",
        CURILLO: "Reg_Centro Oriente",
    },
    CASANARE: {
        YOPAL: "Reg_Centro Oriente",
        TAURAMENA: "Reg_Centro Oriente",
        MONTERREY: "Reg_Centro Oriente",
        AGUAZUL: "Reg_Centro Oriente",
    },
    CAUCA: {
        POPAYAN: "Reg_Cali",
        CALOTO: "Reg_Cali",
        "SANTANDER DE QUILICHAO": "Reg_Cali",
        GUAPI: "Reg_Cali",
        PIENDAMO: "Reg_Cali",
        MIRANDA: "Reg_Cali",
        "PUERTO TEJADA": "Reg_Cali",
        CAJIBIO: "Reg_Cali",
    },
    CESAR: {
        VALLEDUPAR: "Reg_Barranquilla",
        AGUACHICA: "Reg_Barranquilla",
        "EL COPEY": "Reg_Barranquilla",
        "SAN MARTIN": "Reg_Barranquilla",
    },
    CHOCO: {
        QUIBDO: "Reg_Medellin",
        CONDOTO: "Reg_Medellin",
        ISTMINA: "Reg_Medellin",
    },
    CORDOBA: {
        MONTERIA: "Reg_Barranquilla",
        MONTELIBANO: "Reg_Barranquilla",
        "PLANETA RICA": "Reg_Barranquilla",
        SAHAGUN: "Reg_Barranquilla",
        LORICA: "Reg_Barranquilla",
        CERETE: "Reg_Barranquilla",
    },
    CUNDINAMARCA: {
        CAJICA: "Reg_Bogota",
        CHIA: "Reg_Bogota",
        GIRARDOT: "Reg_Bogota",
        "VILLA DE SAN DIEGO DE UBATE": "Reg_Bogota",
        CHOCONTA: "Reg_Bogota",
        FUSAGASUGA: "Reg_Bogota",
        FACATATIVA: "Reg_Bogota",
        ZIPAQUIRA: "Reg_Bogota",
        MOSQUERA: "Reg_Bogota",
        GUADUAS: "Reg_Bogota",
        TOCANCIPA: "Reg_Bogota",
        PACHO: "Reg_Bogota",
        SOPO: "Reg_Bogota",
        SOACHA: "Reg_Bogota",
        FUNZA: "Reg_Bogota",
        VILLETA: "Reg_Bogota",
        "LA CALERA": "Reg_Bogota",
        GUASCA: "Reg_Bogota",
        FOMEQUE: "Reg_Bogota",
        "LA MESA": "Reg_Bogota",
        SILVANIA: "Reg_Bogota",
        SASAIMA: "Reg_Bogota",
        ANOLAIMA: "Reg_Bogota",
        FOSCA: "Reg_Bogota",
        "SAN JUAN DE RIO SECO": "Reg_Bogota",
        "PUERTO SALGAR": "Reg_Bogota",
        GUATAVITA: "Reg_Bogota",
        "AGUA DE DIOS": "Reg_Bogota",
        TOCAIMA: "Reg_Bogota",
        MEDINA: "Reg_Bogota",
        GACHETA: "Reg_Bogota",
        "LA PALMA": "Reg_Bogota",
        "LA VEGA": "Reg_Bogota",
        COGUA: "Reg_Bogota",
        MADRID: "Reg_Bogota",
    },
    "DISTRITO CAPITAL": { BOGOTA: "Reg_Bogota" },
    HUILA: {
        NEIVA: "Reg_Centro Oriente",
        GARZON: "Reg_Centro Oriente",
        PITALITO: "Reg_Centro Oriente",
        RIVERA: "Reg_Centro Oriente",
        YAGUARA: "Reg_Centro Oriente",
        HOBO: "Reg_Centro Oriente",
        CAMPOALEGRE: "Reg_Centro Oriente",
        "SAN AGUSTIN": "Reg_Centro Oriente",
        "LA PLATA": "Reg_Centro Oriente",
        TIMANA: "Reg_Centro Oriente",
    },
    "LA GUAJIRA": {
        RIOHACHA: "Reg_Barranquilla",
        FONSECA: "Reg_Barranquilla",
        "SAN JUAN DEL CESAR": "Reg_Barranquilla",
        BARRANCAS: "Reg_Barranquilla",
        ALBANIA: "Reg_Barranquilla",
        MAICAO: "Reg_Barranquilla",
        VILLANUEVA: "Reg_Barranquilla",
        HATONUEVO: "Reg_Barranquilla",
        URUMITA: "Reg_Barranquilla",
        URIBIA: "Reg_Barranquilla",
        "EL MOLINO": "Reg_Barranquilla",
        DISTRACCION: "Reg_Barranquilla",
        "MUCHAIZA ( LA MINA )": "Reg_Barranquilla",
    },
    MAGDALENA: {
        "SANTA MARTA": "Reg_Barranquilla",
        TENERIFE: "Reg_Barranquilla",
        CIENAGA: "Reg_Barranquilla",
        "NUEVA GRANADA": "Reg_Barranquilla",
    },
    META: {
        VILLAVICENCIO: "Reg_Centro Oriente",
        "PUERTO LOPEZ": "Reg_Centro Oriente",
        ACACIAS: "Reg_Centro Oriente",
        GRANADA: "Reg_Centro Oriente",
        "PUERTO GAITAN": "Reg_Centro Oriente",
        "FUENTE DE ORO": "Reg_Centro Oriente",
        "VISTA HERMOSA": "Reg_Centro Oriente",
        "PUERTO CONCORDIA": "Reg_Centro Oriente",
        "SAN JUAN DE ARAMA": "Reg_Centro Oriente",
        RESTREPO: "Reg_Centro Oriente",
        "BARRANCA DE UPIA": "Reg_Centro Oriente",
        "EL CASTILLO": "Reg_Centro Oriente",
        "LA MACARENA": "Reg_Centro Oriente",
        CABUYARO: "Reg_Centro Oriente",
        CUMARAL: "Reg_Centro Oriente",
        "PUERTO LLERAS": "Reg_Centro Oriente",
        URIBE: "Reg_Centro Oriente",
        "SAN JUANITO": "Reg_Centro Oriente",
        MESETAS: "Reg_Centro Oriente",
        MAPIRIPAN: "Reg_Centro Oriente",
        LEJANIAS: "Reg_Centro Oriente",
        "EL CALVARIO": "Reg_Centro Oriente",
        "CASTILLA LA NUEVA": "Reg_Centro Oriente",
    },
    NARIÑO: {
        PASTO: "Reg_Cali",
        IPIALES: "Reg_Cali",
        "SAN ANDRES DE TUMACO": "Reg_Cali",
        SAMANIEGO: "Reg_Cali",
        TANGUA: "Reg_Cali",
        "EL TAMBO": "Reg_Cali",
    },
    "NORTE DE SANTANDER": {
        CUCUTA: "Reg_Bucaramanga",
        PAMPLONA: "Reg_Bucaramanga",
        TOLEDO: "Reg_Bucaramanga",
        TIBU: "Reg_Bucaramanga",
        OCAÑA: "Reg_Bucaramanga",
        "LOS PATIOS": "Reg_Bucaramanga",
    },
    PUTUMAYO: {
        "VALLE DEL GUAMUEZ": "Reg_Cali",
        "PUERTO ASIS": "Reg_Cali",
        ORITO: "Reg_Cali",
        MOCOA: "Reg_Cali",
        LEGUIZAMO: "Reg_Cali",
    },
    QUINDIO: {
        ARMENIA: "Reg_Medellin",
        SALENTO: "Reg_Medellin",
        CALARCA: "Reg_Medellin",
        QUIMBAYA: "Reg_Medellin",
    },
    RISARALDA: {
        PEREIRA: "Reg_Medellin",
        "SANTA ROSA DE CABAL": "Reg_Medellin",
    },
    "SAN ANDRES Y PROVIDENCIA": { "SAN ANDRES": "Reg_Barranquilla" },
    SANTANDER: {
        BUCARAMANGA: "Reg_Bucaramanga",
        BARRANCABERMEJA: "Reg_Bucaramanga",
        FLORIDABLANCA: "Reg_Bucaramanga",
        "SAN GIL": "Reg_Bucaramanga",
        PIEDECUESTA: "Reg_Bucaramanga",
        BARBOSA: "Reg_Bucaramanga",
        SOCORRO: "Reg_Bucaramanga",
        "LA BELLEZA": "Reg_Bucaramanga",
        CONFINES: "Reg_Bucaramanga",
        GUEPSA: "Reg_Bucaramanga",
        "EL CARMEN DE CHUCURI": "Reg_Bucaramanga",
        "PUERTO WILCHES": "Reg_Bucaramanga",
        BARICHARA: "Reg_Bucaramanga",
        LEBRIJA: "Reg_Bucaramanga",
        MOGOTES: "Reg_Bucaramanga",
        CIMITARRA: "Reg_Bucaramanga",
        LANDAZURI: "Reg_Bucaramanga",
        VELEZ: "Reg_Bucaramanga",
        MALAGA: "Reg_Bucaramanga",
        GUADALUPE: "Reg_Bucaramanga",
        CHARALA: "Reg_Bucaramanga",
    },
    SUCRE: {
        SINCELEJO: "Reg_Barranquilla",
        "SANTIAGO DE TOLU": "Reg_Barranquilla",
        COVEÑAS: "Reg_Barranquilla",
    },
    TOLIMA: {
        HONDA: "Reg_Centro Oriente",
        IBAGUE: "Reg_Centro Oriente",
        FRESNO: "Reg_Centro Oriente",
        MARIQUITA: "Reg_Centro Oriente",
        LERIDA: "Reg_Centro Oriente",
        NATAGAIMA: "Reg_Centro Oriente",
        SUAREZ: "Reg_Centro Oriente",
        ROVIRA: "Reg_Centro Oriente",
        ESPINAL: "Reg_Centro Oriente",
        HERVEO: "Reg_Centro Oriente",
        ORTEGA: "Reg_Centro Oriente",
        VENADILLO: "Reg_Centro Oriente",
        PURIFICACION: "Reg_Centro Oriente",
        CHAPARRAL: "Reg_Centro Oriente",
        PRADO: "Reg_Centro Oriente",
        LIBANO: "Reg_Centro Oriente",
        "SAN ANTONIO": "Reg_Centro Oriente",
        "CARMEN DE APICALA": "Reg_Centro Oriente",
        MELGAR: "Reg_Centro Oriente",
        VILLAHERMOSA: "Reg_Centro Oriente",
    },
    "VALLE DEL CAUCA": {
        CALI: "Reg_Cali",
        PALMIRA: "Reg_Cali",
        "GUADALAJARA DE BUGA": "Reg_Cali",
        TULUA: "Reg_Cali",
        CARTAGO: "Reg_Cali",
        PRADERA: "Reg_Cali",
        "EL CERRITO": "Reg_Cali",
        BUENAVENTURA: "Reg_Cali",
        FLORIDA: "Reg_Cali",
        DAGUA: "Reg_Cali",
        ANDALUCIA: "Reg_Cali",
        YUMBO: "Reg_Cali",
        BUGALAGRANDE: "Reg_Cali",
        CAICEDONIA: "Reg_Cali",
        CANDELARIA: "Reg_Cali",
        GINEBRA: "Reg_Cali",
        "LA UNION": "Reg_Cali",
        ROLDANILLO: "Reg_Cali",
        TORO: "Reg_Cali",
        ZARZAL: "Reg_Cali",
        YOTOCO: "Reg_Cali",
        VERSALLES: "Reg_Cali",
        TRUJILLO: "Reg_Cali",
        JAMUNDI: "Reg_Cali",
        SEVILLA: "Reg_Cali",
    },
    VICHADA: { "PUERTO CARREÑO": "Reg_Centro Oriente" },
};

export const getRegional = (departamento, ciudad) => {
    if (!departamento || !ciudad) return "Desconocido";
    const depUpper = departamento.toUpperCase();
    const ciudadUpper = ciudad.toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g, ""); // Remove accents roughly if needed, though map has them

    // Try direct match first
    if (REGIONALES[depUpper] && REGIONALES[depUpper][ciudadUpper]) {
        return REGIONALES[depUpper][ciudadUpper];
    }

    // If specific city map fails, return a default or "Desconocido". 
    // The table lists specific cities. If a city isn't in the list, what? 
    // Assuming based on patterns or just returning unknown.
    return "Desconocido";
};
